### ISSUE TITLE
No config file found: intellij.edn

### ISSUE THREAD

**Issue by margintop15px** [djblue/portal#138]
Hello
Getting an error saying `No config file found: intellij.edn`
while trying to use intellij plugin

I'm using MacOS 12.5.1
And IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Also I have `[djblue/portal "0.30.0"]` in my lein dependencies
I have a Portal Inspector plugin installed (0.30.0)

my code looks like this:

```clojure
(ns my.core
  (:require
   [portal.api :as p]

(def p (p/open {:launcher :intellij}))
```

Here is a stacktrace

```
Syntax error macroexpanding at (core.clj:1:106).
No config file found: intellij.edn
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3719)
clojure.lang.ExceptionInfo: No config file found: intellij.edn {:options {:launcher :intellij}, :config-file "intellij.edn", :search-paths ("/Users/ts1503/Projects/dtower" "/Users/ts1503/Projects" "/Users/ts1503" "/Users" "/")}
	at portal.runtime.jvm.launcher$get_config.invokeStatic(launcher.clj:25)
	at portal.runtime.jvm.launcher$get_config.invoke(launcher.clj:14)
	at portal.runtime.jvm.launcher$remote_open.invokeStatic(launcher.clj:32)
	at portal.runtime.jvm.launcher$remote_open.invoke(launcher.clj:31)
	at portal.runtime.jvm.launcher$eval3843$fn__3844.invoke(launcher.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at portal.runtime.browser$open.invokeStatic(browser.cljc:113)
	at portal.runtime.browser$open.invoke(browser.cljc:106)
	at portal.runtime.jvm.launcher$open.invokeStatic(launcher.clj:73)
	at portal.runtime.jvm.launcher$open.invoke(launcher.clj:68)
	at portal.api$open.invokeStatic(api.cljc:64)
	at portal.api$open.invoke(api.cljc:54)
	at portal.api$open.invokeStatic(api.cljc:62)
	at portal.api$open.invoke(api.cljc:54)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3714)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7199)
	at clojure.lang.Compiler.eval(Compiler.java:7149)
	at clojure.core$eval.invokeStatic(core.clj:3215)
	at clojure.core$eval.invoke(core.clj:3211)
	at nrepl.middleware.interruptible_eval$evaluate$fn__968$fn__969.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at nrepl.middleware.interruptible_eval$evaluate$fn__968.invoke(interruptible_eval.clj:87)
	at clojure.main$repl$read_eval_print__9206$fn__9209.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9206.invoke(main.clj:437)
	at clojure.main$repl$fn__9215.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__999$fn__1003.invoke(interruptible_eval.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__1067$fn__1071.invoke(session.clj:202)
	at nrepl.middleware.session$session_exec$main_loop__1067.invoke(session.clj:201)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

What I'm doing wrong?
Should I create `intellij.edn` manually?

Please help

**Comment by coyotesqrl** [comment]
The configuration file is created when the Portal tab is opened the first time after Intellij is started; if you open the tab, you'll be able to connect.

The config file is deleted when Intellij is shutdown, so you'll need to re-open the tab on each subsequent restart of the application.

The docs will be updated to reflect the change; there may also be an update to the exception text.

**Comment by djblue** [comment]
@margintop15px Would an exception message like `No config file found: intellij.edn: Please ensure extension is installed and Portal tab is open.` be useful?

**Comment by margintop15px** [comment]
Sorry, didn't get which tab I should open. Do you mean the the portal/open call?

**Comment by djblue** [comment]
If you have the portal extension installed, you should see a tab on the right:

![Screen Shot 2022-09-13 at 2 06 30 PM](https://user-images.githubusercontent.com/1986211/190009512-e3338786-a003-416f-ad16-456e2a550213.png)

**Comment by margintop15px** [comment]
oh, now I'm seeing it.
thanks
ok, it makes sense.
would be nice to have it somewhere in the readme or in the docs
