### ISSUE TITLE
Exception in Plugin Portal Inspector (0.52.2)

### ISSUE THREAD

**Issue by danielmiladinov** [djblue/portal#215]
# Cursive, IntelliJ Versions

- Cursive Plugin Version: `1.13.2-eap5-2023.3`
- IntelliJ Version: 
```IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
Licensed to Chariot Solutions / Daniel Miladinov
Subscription is active until July 18, 2024.
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.tree.experimental.layout.cache=false
  debugger.watches.in.variables=false
  editor.minimap.enabled=true
Non-Bundled Plugins:
  de.femtopedia.diffplugin (2.1.12)
  org.intellij.plugins.hcl (233.13135.65)
  IdeaVIM (2.9.1)
  com.intellij.ideolog (222.3.2.0)
  djblue.portal (0.52.2)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-233)
  com.jetbrains.packagesearch.intellij-plugin (233.11800.8)
  Pythonid (233.14475.28)
  izhangzhihao.rainbow.brackets (2024.2.1)
  com.intellij.bigdatatools.core (233.14475.28)
  com.intellij.bigdatatools.binary.files (233.11799.267)
  com.intellij.bigdatatools.rfs (233.14475.28)
  com.intellij.bigdatatools.metastore.core (233.13135.65)
  com.intellij.bigdatatools.flink (233.13135.103)
  mobi.hsz.idea.gitignore (4.5.2)
  com.cursiveclojure.cursive (1.13.2-eap5-2023.3)
  com.github.brcosta.cljstuffplugin (0.7.11)
  org.intellij.scala (2023.3.27)
  com.intellij.bigdatatools.kafka (233.13135.103)
  com.intellij.bigdatatools.spark (233.13135.103)
  com.intellij.bigdatatools.zeppelin (233.13135.65)
  com.intellij.bigdatatools (233.13135.65)
Kotlin: 233.14475.28-IJ
```

# Exception Stacktrace
```
In file: file:///path/to/file/test.clj

java.lang.IllegalStateException: Attempting to call unbound fn: #'cursive.annotator/annotate-symbol
	at clojure.lang.Var$Unbound.throwArity(Var.java:45)
	at clojure.lang.AFn.invoke(AFn.java:36)
	at clojure.lang.Var.invoke(Var.java:388)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:36)
	at cursive.annotator.ClojureAnnotator$Visitor.visitSymbol(Annotator.kt:23)
	at cursive.psi.impl.symbols.ClEditorSymbol.accept(ClEditorSymbol.java:177)
	at cursive.annotator.ClojureAnnotator.annotate(Annotator.kt:49)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:128)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:106)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:361)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:292)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:321)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:324)
	at ἇऌ.analyze(Unknown Source)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:324)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:324)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:91)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:324)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:287)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:234)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by djblue** [comment]
@danielmiladinov I don't see a Portal namespace in the exception, can you provide more details on what issues you are encountering?

**Comment by danielmiladinov** [comment]
Sorry, @djblue, I was opening a brand new namespace file that Cursive had created for me. The file was almost empty except for the single `ns` form at the top. This exception popped up as a notification and I reflexively opened the issue here hoping that you'd find it useful. I'll close this issue out for now and if I see it happen again I'll be sure to check for a portal namespace before submitting. It might have been that IntelliJ got confused as to which plugin was causing the exception, as I imagine how Cursive and Portal are probably somehow interacting with each other…
