### ISSUE TITLE
After upgrade to 0.8.0 p/close causes timeout error on shutdown hook

### ISSUE THREAD

**Issue by gaberger** [djblue/portal#35]
```
(.addShutdownHook
    (Runtime/getRuntime)
    (Thread. #(p/close)))
```

### Stacktrace

Press CTRL+C to exit
```
^C^CException in thread "Thread-1" clojure.lang.ExceptionInfo: Portal request timeout {:type :sci/error, :line 46, :column 11, :message {:op :portal.rpc/close, :portal.rpc/id 2}, :callstack #object[clojure.lang.Delay 0x3ba0d751 {:status :pending, :val nil}], :file "portal/runtime/jvm/client.clj", :locals {session-id #uuid "be88a78a-47cd-4ba6-a43c-264c36c77adf", message {:op :portal.rpc/close, :portal.rpc/id 2}, temp__8814__auto__ #object[sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887 0x4b1e5a16 "sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887@4b1e5a16"], send! #object[sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887 0x4b1e5a16 "sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887@4b1e5a16"], id 2, response :portal.runtime.jvm.client/timeout}, :session-id #uuid "be88a78a-47cd-4ba6-a43c-264c36c77adf"}
	at sci.impl.utils$rethrow_with_location_of_node.invokeStatic(utils.cljc:106)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:617)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_if.invokeStatic(interpreter.cljc:100)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:601)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:85)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:61)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:570)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:85)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:61)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:570)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:85)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:61)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:570)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_if.invokeStatic(interpreter.cljc:99)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:601)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:85)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:61)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:570)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.fns$parse_fn_args_PLUS_body$fn__12883.invoke(fns.cljc:29)
	at sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887.doInvoke(fns.cljc:53)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at sci.impl.vars.SciVar.invoke(vars.cljc:317)
	at sci.impl.interpreter$fn_call.invokeStatic(interpreter.cljc:567)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:617)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:521)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:530)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:601)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:85)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:61)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:570)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_if.invokeStatic(interpreter.cljc:100)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:601)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:521)
	at sci.impl.interpreter$eval_do.invokeStatic(interpreter.cljc:530)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:601)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_if.invokeStatic(interpreter.cljc:99)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:601)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:85)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:61)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:570)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_if.invokeStatic(interpreter.cljc:100)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:601)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.fns$parse_fn_args_PLUS_body$fn__12883.invoke(fns.cljc:29)
	at sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887.doInvoke(fns.cljc:53)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at sci.impl.interpreter$fn_call.invokeStatic(interpreter.cljc:567)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:617)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_let.invokeStatic(interpreter.cljc:85)
	at sci.impl.interpreter$eval_let.doInvoke(interpreter.cljc:61)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:570)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:521)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:518)
	at sci.impl.fns$parse_fn_args_PLUS_body$fn__12885.invoke(fns.cljc:30)
	at sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887.doInvoke(fns.cljc:53)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at sci.impl.vars.SciVar.invoke(vars.cljc:313)
	at sci.impl.interpreter$fn_call.invokeStatic(interpreter.cljc:567)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:617)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_do_STAR_.invokeStatic(interpreter.cljc:521)
	at sci.impl.interpreter$eval_do_STAR_.invoke(interpreter.cljc:518)
	at sci.impl.fns$parse_fn_args_PLUS_body$fn__12885.invoke(fns.cljc:30)
	at sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887.doInvoke(fns.cljc:53)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at sci.impl.vars.SciVar.invoke(vars.cljc:313)
	at sci.impl.interpreter$fn_call.invokeStatic(interpreter.cljc:567)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:617)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.fns$parse_fn_args_PLUS_body$fn__12883.invoke(fns.cljc:29)
	at sci.impl.fns$parse_fn_args_PLUS_body$run_fn__12887.doInvoke(fns.cljc:53)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: clojure.lang.ExceptionInfo: Portal request timeout {:session-id #uuid "be88a78a-47cd-4ba6-a43c-264c36c77adf", :message {:op :portal.rpc/close, :portal.rpc/id 2}}
	at sci.impl.vars.SciVar.invoke(vars.cljc:317)
	at sci.impl.interpreter$fn_call.invokeStatic(interpreter.cljc:567)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:617)
	at sci.impl.interpreter$interpret.invokeStatic(interpreter.cljc:651)
	at sci.impl.interpreter$interpret.invoke(interpreter.cljc:633)
	at sci.impl.interpreter$eval_throw.invokeStatic(interpreter.cljc:341)
	at sci.impl.interpreter$eval_special_call.invokeStatic(interpreter.cljc:581)
	at sci.impl.interpreter$eval_call.invokeStatic(interpreter.cljc:610)```

**Comment by djblue** [comment]
Hi @gaberger, I can't seem to reproduce this locally. Do you have any additional information? Thanks for reporting the issue.

**Comment by djblue** [comment]
Without any further details, I'm not sure I can be of any help. Please feel free to open this back up with more information.
